{% set name = "modelbase" %}
{% set version = "1.43.6" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 5ba6105acb46e4dbdaaa9de782a90737818e70199dcdb6a8872314099b0a6ae6

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.9
    - pip
    - poetry >=1.5.1
  run:
    - assimulo >=3.4.1
    - black >=23.3.0
    - matplotlib-base >=3.7.1
    - numpy >=1.25.0
    - pandas >=2.0.2
    - python >=3.9
    - python-libsbml >=5.20.1
    - scipy >=1.11.0
    - sympy >=1.12
    - tqdm >=4.65
    - ipywidgets >=8.0.6
    - typing-extensions >=4.6.3

test:
  imports:
    - modelbase
    - modelbase.core
    - modelbase.ode
    - modelbase.ode.models
    - modelbase.ode.simulators
    - modelbase.ode.utils
    - modelbase.utils

about:
  home: https://gitlab.com/qtb-hhu/modelbase-software
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A package to build metabolic models
  doc_url: https://qtb-hhu.gitlab.io/modelbase-software/
  dev_url: https://gitlab.com/qtb-hhu/modelbase-software

extra:
  recipe-maintainers:
    - marvinvanaalst
