{% set name = "modelbase" %}
{% set version = "1.19.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b96f07f30bd62237c6569e21b8744a8b1a95853b97b367c55460bfcd46c29652

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.7
    - pip
    - poetry
  run:
    - assimulo >=3.0
    - black >=22.6
    - matplotlib-base >=3.5
    - numpy >=1.23
    - pandas >=1.4
    - python >=3.7
    - python-libsbml >=5.19
    - scipy >=1.8
    - sympy >=1.10
    - tqdm >=4.64
    - ipywidgets >=7.7
    - typing-extensions >=4.3

test:
  imports:
    - modelbase
    - modelbase.core
    - modelbase.ode
    - modelbase.ode.models
    - modelbase.ode.simulators
    - modelbase.ode.utils
    - modelbase.utils

about:
  home: https://gitlab.com/qtb-hhu/modelbase-software
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A package to build metabolic models
  doc_url: https://qtb-hhu.gitlab.io/modelbase-software/
  dev_url: https://gitlab.com/qtb-hhu/modelbase-software

extra:
  recipe-maintainers:
    - marvinvanaalst
