{% set name = "modelbase" %}
{% set version = "1.57.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fb2f2c9430752bbaa1fe7b67ab8c26267ffed861df494f12dec4274c49b1d863

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.9
    - pip
    - poetry >=1.5.1
  run:
    - assimulo >=3.5.2
    - black >=24.4
    - matplotlib-base >=3.9
    - numpy >=2.0
    - pandas >=2.2
    - python >=3.9
    - python-libsbml >=5.20
    - scipy >=1.13
    - sympy >=1.12
    - tqdm >=4.66
    - ipywidgets >=8.1
    - typing-extensions >=4.12

test:
  imports:
    - modelbase
    - modelbase.core
    - modelbase.ode
    - modelbase.ode.models
    - modelbase.ode.simulators
    - modelbase.ode.utils
    - modelbase.utils

about:
  home: https://gitlab.com/qtb-hhu/modelbase-software
  license: GPL-3.0-or-later
  license_family: GPL3
  license_file: LICENSE
  summary: A package to build metabolic models
  doc_url: https://qtb-hhu.gitlab.io/modelbase-software/
  dev_url: https://gitlab.com/qtb-hhu/modelbase-software

extra:
  recipe-maintainers:
    - marvinvanaalst
    - onewhaleid
